# Generated by Django 5.1.7 on 2025-03-20 21:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(default=api.models.get_current_time),
        ),
    ]
