# Generated by Django 5.1.7 on 2025-03-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction_remove_income_user_delete_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('business services', 'Business Services'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('groceries', 'Groceries'), ('eating out', 'Eating Out'), ('bills', 'Bills'), ('transport', 'Transport'), ('health', 'Health'), ('travel', 'Travel'), ('finance', 'Finance'), ('general', 'General')], max_length=20),
        ),
    ]
