# Generated by Django 5.1.7 on 2025-03-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_transaction_currency_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="name",
            field=models.CharField(default="apple", max_length=100),
            preserve_default=False,
        ),
    ]
