# Generated by Django 5.1.7 on 2025-03-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='BGN', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
